before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq parted -y
  - sudo apt-get install -qq lcov -y
  - source setup.sh

script: make travis -j $(cat /proc/cpuinfo | grep processor | wc -l)

after_success:
  - make codecov-coverage
  - bash <(curl -s https://codecov.io/bash) -X gcov -X coveragepy
